"Chose a color palette appropriate to dark background
set background=dark

"Enable syntax highlighting
syntax on

"Globally change the leader key
let mapleader = "§"

"Enable:
"- filetype detection
"- filetype-based plugin loading from the 'ftplugin' dir
"- filetype-based indent plugins from the 'indent' dir
"https://robots.thoughtbot.com/writing-vim-syntax-plugins
filetype plugin indent on

"Comply to modelines in files
"http://vim.wikia.com/wiki/Modeline_magic
set modeline
"Search modeline in the n first lines of the file
set modelines=5

"Show line numbers
set number
set relativenumber

" Shortcut to rapidly display hidden characters
" http://vimcasts.org/episodes/show-invisibles/
nmap <leader>l :set list!<CR>
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬,space:·


" SEARCH
""""""""
set hlsearch
set incsearch

" Disable highlight until next search
nnoremap <Leader>/ :nohlsearch<CR>


" FINDING FILES
"""""""""""""""
" See https://www.youtube.com/watch?v=XA2WjJbmmoM

" Allow fuzzy-finding filenames
set path+=**
" Display a menubar for tab completion
set wildmenu

"Highlight unwanted spaces
""""""""""""""""""""""""""
"http://vim.wikia.com/wiki/Highlight_unwanted_spaces
highlight ExtraWhitespace ctermbg=red guibg=red

"Show trailing whitespace:
match ExtraWhitespace /\s\+$/
match ExtraWhitespace /\s\+\%#\@<!$/


" SPLIT WINDOWS
"""""""""""""""
set splitright
set splitbelow

" Easily move between split windows
" http://vimcasts.org/episodes/working-with-windows/
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l


" QUICKLIST
"""""""""""
" Moving in the quicklist
nnoremap <Up> :cprevious<CR>
nnoremap <Down> :cnext<CR>
nnoremap <Left> :colder<CR>
nnoremap <Right> :cnewer<CR>


" EXTERNAL MAPPINGS
"""""""""""""""""""
" Remap Caps-Lock to Esc
" This is done at system level, with gnome-tweak-tool
